<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_block px-2 py-3 mt-2 h-52px rounded-l_5154ab_1</name>
   <tag></tag>
   <elementGuidId>301720ab-52a2-4d6d-a6a2-35712ee221d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa5687e7-f6e9-4989-b887-05e4c878b1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eecfe041-ad64-41c0-a97f-84515aba447b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your username</value>
      <webElementGuid>9e181325-e811-4d65-884e-070b03220465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-2 py-3 mt-2 h-[52px] rounded-lg w-full font-semibold border border-base-500 text-primary focus:outline-none focus:border-primary-variant focus:ring-1 focus:ring-primary-variant</value>
      <webElementGuid>b0677d8c-d89e-41c8-89fa-7ebed998c600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex min-h-screen flex-col items-center justify-center py-2 bg-gradient-to-br from-[#51A1E5] to-[#3D2973]&quot;]/main[@class=&quot;flex w-full flex-1 flex-col items-center justify-center px-20 text-center&quot;]/form[1]/section[@class=&quot;bg-white rounded-xl p-5 my-4 w-[500px] mt-7&quot;]/div[@class=&quot;mb-5&quot;]/input[@class=&quot;block px-2 py-3 mt-2 h-[52px] rounded-lg w-full font-semibold border border-base-500 text-primary focus:outline-none focus:border-primary-variant focus:ring-1 focus:ring-primary-variant&quot;]</value>
      <webElementGuid>d892a1a4-0571-48c3-a739-d8c3c86fc52d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>dbce243f-6cc3-4938-9ce3-28630bdc85e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/form/section/div[2]/input</value>
      <webElementGuid>bfc6beaf-1deb-4478-9be3-88e3d545992a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>de554dce-51a4-4393-8fcf-bd25b56899fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Type your username']</value>
      <webElementGuid>992ce2ac-ba06-4848-8836-37e32530a17c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
